# Python, una introducción

Este notebook presenta los conceptos esenciales de Python que suelen aparecer al inicio de un curso de analítica, ciencia de datos o programación aplicada.

## Objetivos de aprendizaje

Al finalizar este material podrás:

- importar módulos y funciones de forma correcta;
- realizar operaciones básicas con números y valores booleanos;
- reconocer los tipos de datos más usados en Python;
- trabajar con listas, tuplas, diccionarios y arrays de `NumPy`;
- aplicar indexación y *slicing*;
- escribir condicionales, bucles y funciones simples.

## Ruta del notebook

1. Importación de librerías  
2. Operaciones básicas  
3. Tipos de datos y estructuras  
4. Indexación y *slicing*  
5. Vectores y arrays con `NumPy`  
6. Conversión de tipos  
7. Comparaciones, condicionales y bucles  
8. Funciones, `lambda` y buenas prácticas


## Importar librerías

En Python, gran parte de la funcionalidad se organiza en **módulos** y **paquetes**.  
Importar correctamente una librería permite reutilizar código ya implementado y mantener programas más claros.


A continuación se realiza un `import` genérico del módulo `math`.  
En este caso se importa el módulo completo y luego se accede a sus funciones con la notación `math.funcion(...)`.


In [29]:
import math
math.sqrt(25)

5.0

Si se desea importar una función específica, se declara luego de `from ... import ...`.  
Esto puede ser útil cuando se necesita una sola función de un módulo.


In [ ]:
# importar una función
from math import sqrt
sqrt(25) # no se requiere tener una referencia al módulo

Cuando se requieren varias funciones de un módulo, se pueden declarar separadas por comas luego de `import`.


In [ ]:
# importar multiples funciones en una llamada
from math import cos, floor


Para importar todas las funciones de un módulo se usa `*`.  
En general **no se recomienda** porque:

- puede sobrescribir nombres ya existentes;
- dificulta identificar de dónde proviene cada función;
- vuelve el código menos legible y menos mantenible.


In [ ]:
# from os import *

También se pueden definir **alias** (nombres cortos o convencionales) para las librerías.  
Esto mejora la legibilidad y evita escribir nombres largos repetidamente.

Por convención, algunos alias muy usados son:

- `import numpy as np`
- `import pandas as pd`
- `import matplotlib.pyplot as plt`


In [ ]:
# Definir un alias
import numpy as np
# mostrar todas las funciones del módulo 'math'
content = dir(math)

## Operaciones básicas

Python permite trabajar con operaciones aritméticas y lógicas de manera muy natural.  
A continuación se muestran los operadores más comunes.


Números:

In [6]:
10 + 4 # suma (salida: 14)

2

In [7]:
10 - 4 # resta (salida 6)

6

In [8]:
10 * 4 # multiplicacion (salida 40)

40

In [9]:
10 ** 4 # exponente (salida 10000)

10000

In [13]:
10 / float(4) # divide (salida 2.5)

2.5

In [14]:
5 % 4 # modulo (salida 1) - también conocido como el resto

1

In [16]:
10 / 4 # division común (salida 2.5)

2.5

In [19]:
5 // 2 # division piso (salida 2)

2

### Operaciones booleanas

Las comparaciones devuelven valores `True` o `False`, que son la base de condicionales y filtros lógicos.


In [30]:
# comparaciones (salida True)
5 > 3
5 >= 3
5 != 3
5 == 5
# operaciones booleanas (salida True)
5 > 3 and 6 > 3
5 > 3 or 5 < 3
not False
False or not False and True # orden de evaluación: not, and, or

True

## Tipos de datos

Comprender el tipo de un objeto es fundamental para anticipar su comportamiento.  
En Python todo es un objeto, y cada objeto tiene un tipo asociado.


Determinar el tipo de un objeto:


In [31]:
type(2) # salida 'int'
type(2.0) # salida 'float'
type('two') # salida 'str'
type(True) # salida 'bool'
type(None) # salida 'NoneType'

NoneType

Revisar si un objeto pertenece a un tipo específico:


In [32]:
isinstance(2.0, int) # salida False
isinstance(2.0, (int, float)) # salida True

True

Convertir un objeto a un tipo específico:


In [34]:
float(2)
int(2.9)
str(2.9)

'2.9'

Cero, `None` y contenedores vacíos se convierten en `False`:


In [35]:
bool(0)
bool(None)
bool('') # string vacío
bool([]) # list vacía
bool({}) # dictionary vacío

False

Contenedores no vacíos y distintos de cero se convierten en `True`:


In [36]:
bool(2)
bool('two')
bool([2])

True

### Mutabilidad: una distinción importante

Una idea clave en Python es diferenciar objetos **mutables** e **inmutables**:

- **mutables**: pueden cambiar después de ser creados, como `list` y `dict`;
- **inmutables**: no cambian, como `tuple`, `int`, `float` y `str`.

Esta diferencia ayuda a entender muchos comportamientos del lenguaje.


### Estructuras de datos integradas en Python

A continuación se resumen algunas estructuras muy usadas:

- **Listas (`list`)**: estructuras ordenadas y **mutables**. Permiten agregar, eliminar o modificar elementos.
- **Tuplas (`tuple`)**: estructuras ordenadas pero **inmutables**. Son útiles cuando los valores no deben cambiar.
- **Diccionarios (`dict`)**: almacenan pares **clave–valor**. Desde Python 3.7 preservan el orden de inserción.
- **Arrays de `NumPy`**: estructuras optimizadas para cálculo numérico y álgebra lineal.
- **`DataFrame` de `pandas`**: tabla bidimensional orientada a análisis de datos.

En esta parte veremos primero listas, tuplas y diccionarios, y luego profundizaremos en arrays.


### Listas (`list`)

Las listas permiten agrupar objetos de cualquier tipo, incluso mezclados.  
Son una de las estructuras más flexibles de Python.


In [8]:
miLista = ["abc","def","hgoj"]

In [9]:
miLista.append("klm")

In [10]:
miLista

['abc', 'def', 'hgoj', 'klm']

In [11]:
miLista2 = [1,2,3]
miLista3 = [4,5,6]

In [12]:
miLista2 +miLista3

[1, 2, 3, 4, 5, 6]

### Tuplas (`tuple`)

Las tuplas agrupan varios elementos, pero a diferencia de las listas son **inmutables**: no pueden modificarse después de crearse.


In [23]:
import numpy as np

In [24]:
miTupla = ('abc', np.arange(0,3,0.2), 2.5)

In [25]:
miTupla[2]

2.5

### Arrays (`numpy.ndarray`)

Los arrays de `NumPy` son la estructura estándar para cálculo numérico eficiente.

Ideas clave:

- un array permite operaciones elemento a elemento;
- el operador `+` suma componente a componente;
- el método `.dot()` permite productos matriciales o productos punto, según la dimensión;
- en `NumPy`, un array de una dimensión (`1D`) **no distingue** entre vector fila y vector columna.  
  Por eso `x.T` no cambia un array `1D`; para representar una columna conviene usar `x.reshape(-1,1)`.


In [13]:
miArray2 = np.array(miLista2)
miArray3 = np.array(miLista3)

In [14]:
miArray2+miArray3

array([5, 7, 9])

In [15]:
miArray2.dot(miArray3)

32

### Diccionarios (`dict`)

Los diccionarios almacenan pares **clave–valor** y se accede a sus elementos mediante `dict[clave]`.  
Se pueden crear con `dict(...)` o usando llaves `{...}`.


In [16]:
miDict = dict(uno = 1, dos = 2, info ='algo de informacion')
miDict2 = {'diez':10, 'veinte':20, 'info':'mas informacion'}

In [17]:
miDict2['info']

'mas informacion'

In [18]:
miDict.keys()

dict_keys(['uno', 'dos', 'info'])

In [19]:
miDict2.get('veinte')

20

### Comparación rápida de estructuras

| Estructura | Ordenada | Mutable | Uso típico |
|---|---:|---:|---|
| `list` | Sí | Sí | colecciones generales |
| `tuple` | Sí | No | datos fijos |
| `dict` | Sí* | Sí | pares clave–valor |
| `numpy.ndarray` | Sí | Sí | cálculo numérico |

\* En Python moderno, los diccionarios preservan el orden de inserción.


### `DataFrame`

Un `DataFrame` es una estructura tabular muy utilizada en ciencia de datos, principalmente a través de la librería `pandas`.  
Más adelante aparecerá con mayor detalle.


## Indexación y *slicing*

Las reglas para acceder a elementos individuales o subconjuntos de listas, tuplas o arrays de `NumPy` son:


In [20]:
 #a[ini:fin] # items desde ini hasta fin-1
 # a[ini:]    # items desde ini hasta el resto del array
 # a[:fin]    # items desde el inicio hasta el final -1
 # a[:]       # todo el array`

También se puede usar `step` con cualquiera de las expresiones anteriores:


`a[ini:fin:step] #empieza en ini hasta fin-1 separados por step`

La idea clave es recordar que la indexación empieza en **0**, no en 1.  
Además, `:fin` representa el **primer índice que no se incluye**.

Los índices también pueden ser negativos, lo que indica que se cuenta desde el final del objeto.


In [21]:
#a[-1] #ultimo ítem del array
#a[-2:] #dos ultimos ítems del array
#a[:-2] #todo excepto los dos últimos ítems`

También `a[:5]` devuelve los 5 primeros elementos, y `a[-5:]` los últimos.

<img src="images/im1.png" width="700" height="200">



Practica la indexación con el siguiente arreglo:


In [22]:
a = [5,4,3,6,8,62,1,2,3,6,8,9]

In [23]:
a[-1:]

[9]

In [35]:
a[-2:]

[8, 9]

In [36]:
a[:-2]

[5, 4, 3, 6, 8, 62, 1, 2, 3, 6]

In [37]:
a[2:12:2]

[3, 8, 1, 3, 8]

### Mini ejercicio

Usa la lista `a` para obtener:

1. los tres primeros elementos;
2. los tres últimos elementos;
3. los elementos en posiciones pares;
4. la lista invertida.


In [38]:
len(a)

12

## Vectores y arrays

`NumPy` es el módulo de Python que vuelve eficiente el trabajo con números y estructuras matriciales.  
Por convención se importa como `np`.


*numpy* es el módulo de python que hace eficiente el trabajo con números. Comúnmente se importa como `np`:

In [2]:
import numpy as np

Podemos crear arrays a partir de listas:


In [14]:
dat1 = [1,2,3,4,5] #lista
arr1 = np.array(dat1) #array de 1 dimensión
dat2 = [range(1,4),range(1,4)]# lista de listas
arr2 = np.array(dat2) # array 2D
arr2.tolist() # convertimos el array a una lista nuevamente

[[1, 2, 3], [1, 2, 3]]

Para examinar algunas propiedades del array, tenemos:


In [20]:
arr1.dtype # float64
arr2.ndim # 2
arr2.shape # (2, 4) - axis 0 es filas, axis 1 es columnas
arr2.size # 8 - número total de elementos
len(arr2) # 2 - tamaño de la primera dimensión (o `axis`)

2

### Creación de arrays especiales

`NumPy` ofrece varias funciones convenientes para crear arrays rápidamente:

- **`np.zeros`**: genera ceros;
- **`np.ones`**: genera unos;
- **`np.random.randn`**: genera valores aleatorios con distribución normal estándar;
- **`np.arange`**: genera secuencias numéricas con inicio, fin y paso;
- **`np.linspace`**: genera valores equiespaciados entre dos extremos.


In [40]:
import numpy as np

In [41]:
np.zeros(3)

array([0., 0., 0.])

In [42]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

- **`np.ones`**: genera unos  
- **`np.random.randn`**: genera números con distribución normal estándar


In [43]:
np.random.randn(10)

array([-0.50326279, -0.30848942, -0.40828325,  0.12509029,  0.04234051,
        0.01804274, -2.56928208,  0.43544629,  0.07421496,  3.42896645])

- **`np.arange`**: genera un rango de números. Los parámetros pueden ser `start`, `end` y `step`.  
  El valor final se **excluye**.


In [44]:
np.arange(3)

array([0, 1, 2])

In [45]:
np.arange(0,3,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [46]:
xLow = np.arange(0,3,0.5)

In [47]:
xHigh = np.arange(3,5,0.5)

In [48]:
xLow

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [49]:
xHigh

array([3. , 3.5, 4. , 4.5])

- **np.linspace**: genera valores espaciados en forma lineal

In [50]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

- **np.array**: genera un array a partir de datos numéricos

In [51]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

Hay algunos detalles de `NumPy` que suelen confundir al inicio. Conviene resaltarlos explícitamente:


- Un array bidimensional puede interpretarse como una colección de filas.  
  Por eso, al seleccionar el primer elemento de una matriz, se obtiene la primera fila.


In [52]:
Amat = np.array([[1,2],[3,4]])

In [53]:
Amat[0]

array([1, 2])

- Un vector `1D` no es lo mismo que una matriz de una fila o una columna.  
  Por eso, un array `1D` no cambia al transponerse, mientras que una matriz `2D` sí.


In [54]:
x = np.arange(3)

In [55]:
Amat = np.array([[1,2],[3,4]])

In [56]:
x.T == x

array([ True,  True,  True])

In [57]:
Amat.T == Amat

array([[ True, False],
       [False,  True]])

### `reshape`

`reshape` permite cambiar la forma de un array sin alterar sus datos, siempre que el número total de elementos se conserve.


In [24]:
arr = np.arange(10,dtype = float).reshape((2,5))
print(arr.shape)
print(arr.reshape(5,2))

(2, 5)
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


Agregamos un eje con `np.newaxis`.  
Este recurso se usa para aumentar la dimensionalidad del array, por ejemplo para pasar de un vector a una matriz columna.


In [35]:
a = np.array([0,1])
print(a.shape)
print("-----")
a_col = a[:,np.newaxis]
print(a_col)
print(a_col.shape)

(2,)
-----
[[0]
 [1]]
(2, 1)


Obtenemos ahora la transpuesta:


In [ ]:
print(a_col.T)

#### `flatten` y `ravel`

`flatten()` siempre devuelve una **copia** plana del array original:


`ravel()` también aplana el array, pero cuando es posible devuelve una **vista** en lugar de una copia.  
En análisis numérico esta diferencia puede ser importante por memoria y rendimiento.


In [52]:
a_col.flatten()

array([0, 1])

### Resumen sobre `axis`, `reshape`, `flatten` y selección

Esta sección sintetiza varias operaciones que aparecen con frecuencia cuando se trabaja con arrays multidimensionales.


Internamente, `NumPy` usa por defecto el orden tipo **C**, es decir, almacenamiento por filas.  
Ese detalle es útil para entender mejor `reshape`, `ravel` y la forma en que se recorren los datos.


<img src="images/resumenReshape.png" width="600" height="500" style="margin-left:auto; margin-right:auto">

In [42]:
x = np.arange(2*3*4)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Hacemos un `reshape` para convertir `x` en un array 3D:


In [44]:
x = x.reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Para seleccionar el primer plano:


In [45]:
print(x[0,:,:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Para seleccionar las primeras filas:


In [46]:
print(x[:,0,:])

[[ 0  1  2  3]
 [12 13 14 15]]


Para seleccionar las primeras columnas:


In [47]:
print(x[:,:,0])

[[ 0  4  8]
 [12 16 20]]


Veamos ahora un ejemplo simple con una matriz `2D`.

Obtendremos la segunda fila y la tercera columna:


In [50]:
arr = np.arange(10, dtype = float).reshape((2,5))
print(arr)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


Aplicamos `ravel()`:


In [51]:
print(x.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## Conversiones entre tipos de datos

En ocasiones necesitamos transformar objetos entre distintos tipos.  
Las funciones `int`, `float` y `str` son especialmente útiles para esa tarea.


En ocasiones necesitamos transformar datos entre *tipos*. Las funciones `int`, `float` y `str` nos ayudan en esta tarea. Veamos unos ejemplos

In [9]:
print(3.14, int(3.14))

3.14 3


In [10]:
print(3.9999, int(3.9999)) # No se redondea al enterno más próximo

3.9999 3


In [11]:
print(3.0, int(3.0))

3.0 3


In [13]:
print(9, float(9))

9 9.0


In [14]:
print("2345",int("2345")) # El string se convierte en int

2345 2345


In [53]:
#print(int("23covid"))

In [17]:
print(type("23.45"))

<class 'str'>


Una tarea común es concatenar *strings* con valores numéricos. Veamos algunas opciones:


In [2]:
val = 5+3
#print("El valor es: " + val)

In [3]:
print("El valor es: " , val) #Solucion 1

El valor es:  8


In [4]:
print("El valor es: " + str(val)) #Solucion 1

El valor es: 8


También existen **operadores aumentados** como `a += b`.  
Sus equivalencias se muestran a continuación:


|   	|             	|
|----	|-----------------	|
| a+=b  	| a = a+b            	|
| a-=b  	| a = a-b           	|
| a*=b  	| a = a*b  	|
| a/=b  	| a = a/b        	|
| a**=b 	| a = a**b  	|
| a%=b  	| a = a%b 	|

### Operadores de comparación


| Operador | Significado |
|---|---|
| `<`  | Menor que |
| `>`  | Mayor que |
| `<=` | Menor o igual que |
| `>=` | Mayor o igual que |
| `==` | Igual a |
| `!=` | Distinto de |


Los números de distintos tipos (`int`, `float`, etc.) pueden compararse entre sí.  
En cambio, si intervienen tipos incompatibles como `str`, el resultado puede ser diferente o producir error según el caso.


In [27]:
a = 2 # Int

In [28]:
b = 1.99 #float

In [29]:
c = '2' # str

In [30]:
print(a>b)

True


### Nota práctica

Cuando combines condiciones, recuerda el significado de:

- `and`: ambas condiciones deben cumplirse;
- `or`: basta con que una se cumpla;
- `not`: niega una condición.


In [31]:
print(a>b and a!=c)

True


In [32]:
print(a>b or a ==b)

True


### Condicionales


**`if`**


```python
if condicion:
    bloque
```


Ejecuta un bloque de sentencias (que deben estar **indentadas**) si la condición es verdadera.  
Un condicional `if` puede ir seguido de uno o varios `elif` ("else if").


```python
elif condicion:
    bloque
```


También se puede usar `else`:


```python
else:
    bloque
```


Definamos una función simple para evaluar condicionales:


In [35]:
def signo_de_a(a):
    if(a < 0.0):
        signo = 'negativo'
    elif(a>0.0):
        signo = 'positivo'
    else: 
        signo = 'zero'
    return(signo)
            

### Mini ejercicio

Modifica la función `signo_de_a` para que también identifique si el valor es un número entero positivo, entero negativo o cero.


In [38]:
a = 1.5
print('El signo de a es: '+ signo_de_a(a))

El signo de a es: positivo


### Bucles


**`while`**


```python
while condicion:
    bloque
```


Ejecuta el bloque de sentencias mientras la condición sea verdadera.  
Después de cada iteración, la condición se vuelve a evaluar.


In [2]:
nMax = 5
n = 1
a = [] # creamos una lista vacía
while n < nMax:
    a.append(1.0/n) # agregamos un elemento a la lista
    n += 1
print(a)

[1.0, 0.5, 0.3333333333333333, 0.25]


## `for`


Esta sentencia necesita una variable objetivo y una secuencia sobre la que iterar. Su forma general es:


```python
for objetivo in secuencia:
    bloque
```


También es posible añadir un `else` después del `for` si es necesario (y aplica también para `while`).


In [4]:
nMax = 5
a = []
for n in range(1,nMax):
    a.append(1.0/n)
print(a)

[1.0, 0.5, 0.3333333333333333, 0.25]


Aquí `n` es la variable objetivo y la secuencia se crea con la función `range`.  
Veamos un ejemplo más completo que busca un nombre en una lista:


In [11]:
lista = ["Julio","Jammie","Gina","David"]
name = "Tito"#eval(input("Escriba un nombre: ")) #Codigo para ingresar datos
for i in range(len(lista)):
    if lista[i] == name:
        print( name, 'es número', i+1, 'en la lista')
        break
else:
    print( name, 'no está en la lista')

Tito no está en la lista


### `continue`


La sentencia `continue` permite saltar el resto del código dentro de una iteración y pasar inmediatamente a la siguiente.

El siguiente ejemplo construye una lista con todos los números entre 1 y 99 divisibles para 7.


### Sugerencia de estilo

En muchos casos, cuando solo necesitas iterar sobre una secuencia, es preferible:

- usar `for elemento in secuencia` en lugar de índices;
- usar `enumerate(...)` cuando además necesitas la posición.


In [13]:
x = [] # creamos una lista vacía
for i in range(1,100):
    if i%7!=0: continue # Si no es divisible para 7, no se ejecuta el resto
    x.append(i) # agregamos i a la lista
print(x)

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]


## Programas en Python
### Funciones, módulos y paquetes


- **Función**: se define con la palabra clave `def` y normalmente devuelve un resultado con `return`.
- **Módulo**: es un archivo con extensión `.py` que contiene funciones, clases o variables.
- **Paquete**: es una carpeta que agrupa módulos relacionados; normalmente incluye un archivo `__init__.py`.


**Funciones**

In [59]:
'''Demostración de una función de python
author: thomas haslwanter, date: May-2015
'''

# Importamos los paquetes
import numpy as np

def incomeAndExpenses(data):
    '''Encuentre la suma de valores positivos, y la suma de valores negativos.'''
    income = np.sum(data[data>0])
    expenses = np.sum(data[data<0])
    return(income,expenses)



In [60]:
testData = np.array([-5,12, 3, -6, -4, 8])
(myIncome,myExpenses) = incomeAndExpenses(testData)
print('Has ganado USD {0:5.2f} y gastado USD {1:5.2f}'.format(myIncome,-myExpenses))

Has ganado USD 23.00 y gastado USD 15.00


El número de parámetros en la definición de una función puede ser arbitrario. Por ejemplo, en la definición:


`def func(x1,x2,*x3)`

`x1` y `x2` son parámetros posicionales.  
En cambio, `*x3` representa una tupla de longitud arbitraria que agrupa argumentos adicionales.

Si llamamos a la función `func(a, b, c, d, e)`, entonces:

- `a` corresponde a `x1`
- `b` corresponde a `x2`
- `c, d, e` quedan agrupados dentro de `x3`


### Funciones `lambda`


Si una función puede expresarse en una sola línea, se puede definir con `lambda`:

```python
func_name = lambda param1, param2, ...: expresion
```

Solo se permite **una expresión**. Un ejemplo:


In [61]:
c = lambda x,y: x**2 + y**2
print(c(3,4))

25


## Buenas prácticas en Python

PEP 8 es el estándar más conocido de estilo para Python: <https://peps.python.org/pep-0008/>.

Algunas recomendaciones básicas:


1. Usa nombres descriptivos para variables y funciones.
2. Mantén una indentación consistente de 4 espacios.
3. Prefiere `snake_case` para funciones y variables.
4. Importa librerías con sus alias convencionales (`np`, `pd`, `plt`).
5. Escribe comentarios solo cuando aporten contexto real.
6. Documenta las funciones con *docstrings*.
7. Evita `from modulo import *` salvo que exista una razón pedagógica muy concreta.

## Cierre

En este notebook revisaste la sintaxis inicial de Python y varias estructuras que serán la base para notebooks posteriores del curso.
